name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: [build, test]
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: ${{ matrix.action }}
      run: swift ${{ matrix.action }}
